const fs = require('fs');
const path = require('path');

// ファイルパスの設定（ルートディレクトリを基準にする）
const inputPath = path.join(__dirname, '../summary.txt');
const outputPath = path.join(__dirname, '../index.html');

try {
    // summary.txt を読み込む
    const content = fs.readFileSync(inputPath, 'utf8');

    // HTMLのテンプレート
    const html = `
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>重要ニュース要約</title>
    <style>
        body { font-family: "Helvetica Neue", Arial, "Hiragino Kaku Gothic ProN", "BIZ UDPGothic", sans-serif; line-height: 1.8; color: #333; max-width: 900px; margin: 0 auto; padding: 20px; background-color: #f0f2f5; }
        .card { background: white; padding: 40px; border-radius: 16px; box-shadow: 0 10px 25px rgba(0,0,0,0.05); }
        h1 { border-left: 5px solid #007bff; padding: 0 15px; color: #1a1a1a; font-size: 28px; margin-bottom: 30px; }
        .content { white-space: pre-wrap; font-size: 17px; color: #444; }
        .date { text-align: right; color: #888; margin-bottom: 10px; font-weight: bold; }
        hr { border: 0; border-top: 1px solid #eee; margin: 30px 0; }
        footer { margin-top: 40px; font-size: 13px; color: #aaa; text-align: center; }
    </style>
</head>
<body>
    <div class="card">
        <div class="date">${new Date().toLocaleString('ja-JP', { timeZone: 'Asia/Tokyo' })} 更新</div>
        <h1>📰 本日の重要ニュース要約</h1>
        <div class="content">${content}</div>
    </div>
    <footer>Generated by Gemini AI & GitHub Actions</footer>
</body>
</html>
`;

    fs.writeFileSync(outputPath, html);
    console.log('Successfully generated index.html in the root directory.');
} catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
}
