const fs = require('fs');

// summary.txt を読み込む
const content = fs.readFileSync('summary.txt', 'utf8');

// HTMLのテンプレート
const html = `
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ニュース抽出</title>
    <style>
        body { font-family: "Helvetica Neue", Arial, sans-serif; line-height: 1.8; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; background-color: #f9f9f9; }
        .card { background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1 { border-bottom: 3px solid #007bff; padding-bottom: 10px; color: #007bff; font-size: 24px; }
        .content { white-space: pre-wrap; font-size: 16px; }
        footer { margin-top: 30px; font-size: 12px; color: #888; text-align: center; }
    </style>
</head>
<body>
    <div class="card">
        <h1>📰 ニュース抽出 (${new Date().toLocaleDateString('ja-JP')})</h1>
        <div class="content">${content}</div>
    </div>
    <footer>Generated by Gemini AI</footer>
</body>
</html>
`;

// index.html として保存
fs.writeFileSync('index.html', html);
console.log('index.html has been generated.');
